name: mcscan-binderized
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7.*
  - scipy
  - numpy
  - last
  - pandas-datareader>=0.5.0
  - statsmodels
  - regex
  - perl=5.22.0.1
  - pip:
    - jcvi
    - wand
    - matplotlib
    - seaborn
